function ydot = FHN_rhs_fn(in1,in2)
%FHN_RHS_FN
%    YDOT = FHN_RHS_FN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    04-Feb-2014 15:34:30

R = in1(2,:);
V = in1(1,:);
a = in2(1,:);
b = in2(2,:);
c = in2(3,:);
t2 = V.^2;
ydot = [c.*(R+V-V.*t2.*(1.0./3.0));-(V-a+R.*b)./c];
