function Sdot = FHN_sens_rhsV_fn(in1,in2,in3,in4)
%FHN_SENS_RHSV_FN
%    SDOT = FHN_SENS_RHSV_FN(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    04-Feb-2014 15:34:31

R = in1(2,:);
SR1 = in3(:,1);
SR2 = in3(:,2);
SR3 = in3(:,3);
SR4 = in3(:,4);
SR5 = in3(:,5);
SV1 = in2(:,1);
SV2 = in2(:,2);
SV3 = in2(:,3);
SV4 = in2(:,4);
SV5 = in2(:,5);
V = in1(1,:);
c = in4(3,:);
t2 = V.^2;
t3 = t2-1.0;
Sdot = [SR1.*c-SV1.*c.*t3,SR2.*c-SV2.*c.*t3,SR3.*c-SV3.*c.*t3,SR4.*c-SV4.*c.*t3,R+V+SR5.*c-V.*t2.*(1.0./3.0)-SV5.*c.*t3];
