function dB = FHN_rhsR_fn(in1,in2)
%FHN_RHSR_FN
%    DB = FHN_RHSR_FN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    04-Feb-2014 15:34:30

R = in1(2,:);
V = in1(1,:);
a = in2(1,:);
b = in2(2,:);
c = in2(3,:);
dB = -(V-a+R.*b)./c;
