function Sdot = FHN_sens_rhs_fn(in1,in2,in3)
%FHN_SENS_RHS_FN
%    SDOT = FHN_SENS_RHS_FN(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    31-Jan-2014 04:44:44

R = in1(2,:);
SR1 = in2(6);
SR2 = in2(7);
SR3 = in2(8);
SR4 = in2(9);
SR5 = in2(10);
SV1 = in2(1);
SV2 = in2(2);
SV3 = in2(3);
SV4 = in2(4);
SV5 = in2(5);
V = in1(1,:);
a = in3(1,:);
b = in3(2,:);
c = in3(3,:);
t2 = 1.0./c;
t3 = V.^2;
t4 = t3-1.0;
Sdot = reshape([-SR1.*t2-SV1.*c.*t4,-SR2.*t2-SV2.*c.*t4,-SR3.*t2-SV3.*c.*t4,-SR4.*t2-SV4.*c.*t4,R+V-SR5.*t2-V.*t3.*(1.0./3.0)-SV5.*c.*t4,SV1.*c-SR1.*b.*t2,SV2.*c-SR2.*b.*t2,t2+SV3.*c-SR3.*b.*t2,SV4.*c-R.*t2-SR4.*b.*t2,SV5.*c+1.0./c.^2.*(V-a+R.*b)-SR5.*b.*t2],[5, 2]);
