function dA = FHN_rhsV_fn(in1,in2)
%FHN_RHSV_FN
%    DA = FHN_RHSV_FN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    04-Feb-2014 15:34:29

R = in1(2,:);
V = in1(1,:);
c = in2(3,:);
t2 = V.^2;
dA = c.*(R+V-V.*t2.*(1.0./3.0));
