function Sdot = FHN_sens_rhsR_fn(in1,in2,in3,in4)
%FHN_SENS_RHSR_FN
%    SDOT = FHN_SENS_RHSR_FN(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    04-Feb-2014 15:34:31

R = in1(2,:);
SR1 = in3(:,1);
SR2 = in3(:,2);
SR3 = in3(:,3);
SR4 = in3(:,4);
SR5 = in3(:,5);
SV1 = in2(:,1);
SV2 = in2(:,2);
SV3 = in2(:,3);
SV4 = in2(:,4);
SV5 = in2(:,5);
V = in1(1,:);
a = in4(1,:);
b = in4(2,:);
c = in4(3,:);
t2 = 1.0./c;
Sdot = [-SV1.*t2-SR1.*b.*t2,-SV2.*t2-SR2.*b.*t2,t2-SV3.*t2-SR3.*b.*t2,-R.*t2-SV4.*t2-SR4.*b.*t2,-SV5.*t2+1.0./c.^2.*(V-a+R.*b)-SR5.*b.*t2];
