function ydot = model1_rhs_fn(in1,in2)
%MODEL1_RHS_FN
%    YDOT = MODEL1_RHS_FN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    06-Feb-2014 03:10:08

A = in1(1,:);
B = in1(2,:);
Ka = in2(7,:);
Kb = in2(8,:);
k0 = in2(2,:);
k1 = in2(3,:);
k2 = in2(4,:);
k3 = in2(5,:);
k4 = in2(6,:);
m = in2(9,:);
n = in2(10,:);
nu = in2(1,:);
t2 = B.^n;
ydot = [k0-A.*k1+nu./((B./Ka).^m+1.0);A.*k2-B.*k4+(A.*k3.*t2)./(t2+Kb.^n)];
