function dB = model1_rhsB_fn(in1,in2)
%MODEL1_RHSB_FN
%    DB = MODEL1_RHSB_FN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    06-Feb-2014 03:10:07

A = in1(1,:);
B = in1(2,:);
Kb = in2(8,:);
k2 = in2(4,:);
k3 = in2(5,:);
k4 = in2(6,:);
n = in2(10,:);
t2 = B.^n;
dB = A.*k2-B.*k4+(A.*k3.*t2)./(t2+Kb.^n);
