function jac = model1_jac_fn(in1,in2)
%MODEL1_JAC_FN
%    JAC = MODEL1_JAC_FN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    06-Feb-2014 03:10:08

A = in1(1,:);
B = in1(2,:);
Ka = in2(7,:);
Kb = in2(8,:);
k1 = in2(3,:);
k2 = in2(4,:);
k3 = in2(5,:);
k4 = in2(6,:);
m = in2(9,:);
n = in2(10,:);
nu = in2(1,:);
t2 = 1.0./Ka;
t3 = B.*t2;
t4 = B.^n;
t5 = Kb.^n;
t6 = t4+t5;
t7 = 1.0./t6;
t8 = n-1.0;
t9 = B.^t8;
jac = reshape([-k1,k2+k3.*t4.*t7,-m.*nu.*t2.*t3.^(m-1.0).*1.0./(t3.^m+1.0).^2,-k4+A.*k3.*n.*t7.*t9-A.*k3.*n.*t4.*1.0./t6.^2.*t9],[2, 2]);
