function dA = model1_rhsA_fn(in1,in2)
%MODEL1_RHSA_FN
%    DA = MODEL1_RHSA_FN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    06-Feb-2014 03:10:07

A = in1(1,:);
B = in1(2,:);
Ka = in2(7,:);
k0 = in2(2,:);
k1 = in2(3,:);
m = in2(9,:);
nu = in2(1,:);
dA = k0-A.*k1+nu./((B./Ka).^m+1.0);
