function SBdot = model1_sens_rhsB_fn(in1,in2,in3,in4)
%MODEL1_SENS_RHSB_FN
%    SBDOT = MODEL1_SENS_RHSB_FN(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    06-Feb-2014 03:10:11

A = in1(1,:);
B = in1(2,:);
Kb = in4(8,:);
SA1 = in2(:,1);
SA2 = in2(:,2);
SA3 = in2(:,3);
SA4 = in2(:,4);
SA5 = in2(:,5);
SA6 = in2(:,6);
SA7 = in2(:,7);
SA8 = in2(:,8);
SA9 = in2(:,9);
SA10 = in2(:,10);
SB1 = in3(:,1);
SB2 = in3(:,2);
SB3 = in3(:,3);
SB4 = in3(:,4);
SB5 = in3(:,5);
SB6 = in3(:,6);
SB7 = in3(:,7);
SB8 = in3(:,8);
SB9 = in3(:,9);
SB10 = in3(:,10);
k2 = in4(4,:);
k3 = in4(5,:);
k4 = in4(6,:);
n = in4(10,:);
t2 = B.^n;
t3 = n-1.0;
t4 = B.^t3;
t5 = Kb.^n;
t6 = t2+t5;
t7 = 1.0./t6;
t8 = 1.0./t6.^2;
t9 = A.*k3.*n.*t2.*t4.*t8;
t13 = A.*k3.*n.*t4.*t7;
t10 = k4+t9-t13;
t11 = k3.*t2.*t7;
t12 = k2+t11;
SBdot = [SA1.*t12-SB1.*t10,SA2.*t12-SB2.*t10,SA3.*t12-SB3.*t10,SA4.*t12-SB4.*t10,SA5.*t12-SB5.*t10,A+SA6.*t12-SB6.*t10,SA7.*t12-SB7.*t10+A.*t2.*t7,-B+SA8.*t12-SB8.*t10,SA9.*t12-SB9.*t10,SA10.*t12-SB10.*t10-A.*Kb.^t3.*k3.*n.*t2.*t8];
